Repository Limitless-Blue/Ed-AI, pull requests merged in 2025-02, with the labels that each got.

#57 Update .mp3 to .opus
  API_Endpoint/Temp_Static_data/Chat/Response.opus
  API_Endpoint/Temp_Static_data/Profile/greeting_audio.opus
  API_Endpoint/main.py
Labels: Dev Task

#58 Request: Placeholder API Endpoints, Middleware, and IDs Updates
  .gitignore
  API_Endpoint/main.py
  Dev Plans/Static Material Plan.md
Labels: documentation, Dev Task

#68 Added interview functions, landing page functions, and resume functions to the original API code.
  API_Endpoint/Temp_Static_data/Chat/Response.mp3
  API_Endpoint/Temp_Static_data/Chat/Test_output_speed_up.mp3
  API_Endpoint/Temp_Static_data/Chat/cover_letter.txt
  Database/AI_Database/Vector_Database/36bb5fbf-fc51-4334-bdf0-a8cb5efcccde/length.bin
  Database/AI_Database/Vector_Database/chroma.sqlite3
  Database/AI_Database/Vector_Database/f9a6f2b2-cc58-4e6f-bbea-624be5a41d52/data_level0.bin
  Database/AI_Database/Vector_Database/f9a6f2b2-cc58-4e6f-bbea-624be5a41d52/header.bin
  Database/AI_Database/Vector_Database/f9a6f2b2-cc58-4e6f-bbea-624be5a41d52/length.bin
  Database/AI_Database/Vector_Database/f9a6f2b2-cc58-4e6f-bbea-624be5a41d52/link_lists.bin
  api/api_functions/exp.py
  api/api_functions/interview_functions.py
  api/api_functions/jobs_functions.py
  api/api_functions/landing_functions.py
  api/api_functions/learn_functions.py
  api/api_functions/resume_functions.py
  api/interview.py
  api/jobs.py
  api/landing.py
  api/learn.py
  api/practice.py
  api/resume.py
  api/settings.py
  cover_letter.txt
  exp.ipynb
Labels: enhancement, Dev Task

#69 Replace placeholder API code with Working API code
  !Archive/requirements copy.txt
  API_Endpoint/placeholder_main.py
  Database/Redirection/Recommedations_(dynamic_version).json
  Test_Recording.mp3
  Test_Recording.wav
  api/api_functions/common_functions.py
  api/api_functions/exp.py
  api/api_functions/learn_functions.py
  api/api_functions/practice_functions.py
  api/learn.py
  api/practice.py
  api_exp.ipynb
  cover_letter.txt
  requirements.txt
Labels: enhancement, Dev Task

#118 Dev frontend
  ed-ai/src/App.jsx
  ed-ai/src/assets/Temp_Static_data/Chat/Response.mp3
  ed-ai/src/assets/Temp_Static_data/Chat/Response.opus
  ed-ai/src/assets/Temp_Static_data/JobSearchOptimization/CoverLetter.txt
  ed-ai/src/assets/Temp_Static_data/JobSearchOptimization/generated_resume.pdf
  ed-ai/src/assets/Temp_Static_data/Learn Page/DSA_Intro_1.json
  ed-ai/src/assets/Temp_Static_data/Learn Page/DSA_Intro_1.md
  ed-ai/src/assets/Temp_Static_data/Learn Page/DSA_Intro_2.json
  ed-ai/src/assets/Temp_Static_data/Learn Page/DSA_Intro_2.md
  ed-ai/src/assets/Temp_Static_data/Learn Page/DSA_Intro_3.json
  ed-ai/src/assets/Temp_Static_data/Learn Page/DSA_Intro_3.md
  ed-ai/src/assets/Temp_Static_data/Practice Page/CodingProblem/Concatenation_of_Array.md
  ed-ai/src/assets/Temp_Static_data/Practice Page/CodingProblem/Concatenation_of_Array_solution.py
  ed-ai/src/assets/Temp_Static_data/Practice Page/MCQ/Programming_Fundamentals_000001.json
  ed-ai/src/assets/Temp_Static_data/Profile/greeting_audio.mp3
  ed-ai/src/assets/Temp_Static_data/Profile/greeting_audio.opus
  ed-ai/src/assets/Temp_Static_data/Profile/user_image.png
  ed-ai/src/assets/style/chat.css
  ed-ai/src/assets/style/courseContent.css
  ed-ai/src/assets/style/coursePages.css
  ed-ai/src/assets/style/resumeOptimizer.css
  ed-ai/src/components/codingTest.jsx
  ed-ai/src/components/courseContent.jsx
  ed-ai/src/components/learn.jsx
  ed-ai/src/components/mcqTest.jsx
  ed-ai/src/components/resumeOptimizer.jsx
Labels: enhancement, Dev Task
